source 'https://rubygems.org'
gem 'redd', '0.6.4', :path => './redd/'
gem 'cinch'
gem 'cinch-identify'
gem 'imgur-api', '0.0.4', :path => './imgur/'
gem 'kramdown'
gem 'htmlentities', '~> 4.3.2'
gem 'liquid'
gem 'filewatcher'
gem 'pqueue'
gem 'sqlite3-ruby'
gem 'rmagick', '2.13.4'
gem 'activesupport'
gem 'less', '~> 2.6.0'
gem "therubyracer"